### ISSUE TITLE
Ссылки модуля

### ISSUE THREAD

**Issue by ApexWire** [brussens/yupe-message#19]
Хотелось бы чтобы ссылки были вида:
<site>/message/inbox
<site>/message/outbox
и т.д.

**Comment by yupe** [comment]
Поддерживаю +)

**Comment by brussens** [comment]
@ApexWire , @yupe дело в том, что изначально так делал, но столкнулся с ошибкой, просто не работают пути

**Comment by brussens** [comment]
Спасибо,всё готово d1db94abb7e9b90d9d56699b4ad17cea4a8b2e68
