### ISSUE TITLE
Виджет вместо textAreaGroup

### ISSUE THREAD

**Issue by ApexWire** [brussens/yupe-message#21]
Я бы заменил textAreaGroup ( https://github.com/brussens/yupe-message/blob/master/views/message/compose.php#L47 ) на виджет Textarea ( https://github.com/yupe/yupe/blob/master/protected/modules/yupe/widgets/editors/Textarea.php )

**Comment by brussens** [comment]
Спасибо. cb1f102fc8861e24fb9b43f82701a65a8c342dc4
