### ISSUE TITLE
Фильтры в админке

### ISSUE THREAD

**Issue by yupe** [brussens/yupe-message#23]
Думаю, лучше сделать выпадающими списками

![yupe](https://cloud.githubusercontent.com/assets/668145/6426380/6c1855b8-bf68-11e4-9d09-f5d579cadf1e.jpeg)

**Comment by brussens** [comment]
@yupe не проблема, поправим

**Comment by brussens** [comment]
Поправил. 6192985767ef0239b38cc9a3b899e60496a42a03. Извиняюсь за долгое отсутствие.
